export enum SkEventSnake {
    START_GAME_SNAKE = 'start_game_snake',
    DIRECTION_SNAKE = 'direction_snake',
    PAUSING_SNAKE = 'pausing_snake',
    NEW_GAME_SNAKE = 'new_game_snake',
    ALL_GAME_SNAKE = 'all_game_snake',
    JOIN_SNAKE_QUEUE = 'join_snake_queue_snake',
    MATCH_USER_SNAKE = 'match_user_snake',
    LEAVE_QUEUE_SNAKE = 'leave_queue_snake',
    UPDATE_ROOM_SNAKE = 'update_room_snake',
    QUERY_ROOM_SNAKE = 'query_room_snake',
    END_GAME_SNAKE = 'end_game_snake',
    CREATE_NEW_GAME_SNAKE = 'create_new_game_snake',
    RESET_GAME_SNAKE = 'reset_snake_game_snake',
}

export enum SkEventGalaxy {
    START_GAME_GALAXY = 'start_game_galaxy',
    DIRECTION_GALAXY = 'direction_galaxy',
    PAUSING_GALAXY = 'pausing_galaxy',
    NEW_GAME_GALAXY = 'new_game_galaxy',
    ALL_GAME_GALAXY = 'all_game_galaxy',
    JOIN_GALAXY_QUEUE = 'join_galaxy_queue_galaxy',
    MATCH_USER_GALAXY = 'match_user_galaxy',
    LEAVE_QUEUE_GALAXY = 'leave_queue_galaxy',
    UPDATE_ROOM_GALAXY = 'update_room_galaxy',
    QUERY_ROOM_GALAXY = 'query_room_galaxy',
    END_GAME_GALAXY = 'end_game_galaxy',
    CREATE_NEW_GAME_GALAXY = 'create_new_game_galaxy',
    RESET_GAME_GALAXY = 'reset_galaxy_game_galaxy',
    SHOT_GALAX = 'SHOT_GALAXY',
}
